FROM dolfinx/dolfinx:stable
LABEL version=0.1
RUN 'pip install --no-cache-dir jsonpickle \
debugpy \
platformdirs \
jupyter_core \
importlib-metadata \
jupyter_client \
comm \
pyzmq \
psutil \
tqdm \
tornado \
peewee \
yapf \
ipykernel \
nest-asyncio \
zipp'
WORKDIR /home
COPY . .
EXPOSE 3306