FROM dolfinx/dolfinx:nightly
LABEL version=0.1
RUN pip install jsonpickle \
debugpy \
platformdirs \
jupyter_core \
importlib-metadata \
jupyter_client \
comm \
pyzmq \
psutil \
tqdm \
tornado \
peewee \
yapf \
ipykernel \
nest-asyncio \
zipp
COPY module_setup /tmp/fenics
WORKDIR /tmp/fenics
RUN pip install .
EXPOSE 3306